version: "3"

networks:
  proxiable:
    name: proxiable
    external: true

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - proxiable

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      - SUBDOMAIN=direct
      - PROXIED=true

  lca-data-graphql-server:
    container_name: lca-data-graphql-server
    image: "lca-data-graphql-server"
    restart: always
    environment:
      - DATABASE_URL=${PRISMA_DATABASE_URL}
      - NODE_ENV=production
    networks:
      - proxiable

  lca-data-react-app:
    container_name: lca-data-react-app
    image: "lca-data-react-app"
    restart: always
    networks:
      - proxiable
