/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    /**
     * The `BigInt` scalar type represents non-fractional signed whole numeric values.
     */
    bigInt<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "BigInt";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    /**
     * The `BigInt` scalar type represents non-fractional signed whole numeric values.
     */
    bigInt<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "BigInt";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  LCADisclosureOrderByInput: { // input type
    beginDate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    decisionDate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    receivedDate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    wageRateOfPayFrom?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
}

export interface NexusGenEnums {
  SortOrder: "asc" | "desc"
  casestatus: "Certified" | "Certified___Withdrawn" | "Denied" | "Withdrawn"
  payunit: "Bi_Weekly" | "Hour" | "Month" | "Week" | "Year"
  visaclass: "E_3_Australian" | "H_1B" | "H_1B1_Chile" | "H_1B1_Singapore"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  BigInt: any
  DateTime: any
}

export interface NexusGenObjects {
  Employer: { // root type
    city: string; // String!
    naicsCode: string; // String!
    name: string; // String!
    postalCode: string; // String!
    state?: string | null; // String
    uuid: string; // ID!
  }
  LCADisclosure: { // root type
    beginDate: NexusGenScalars['DateTime']; // DateTime!
    caseNumber: string; // ID!
    caseStatus: NexusGenEnums['casestatus']; // casestatus!
    decisionDate: NexusGenScalars['DateTime']; // DateTime!
    fullTimePosition: boolean; // Boolean!
    jobTitle?: string | null; // String
    prevailingWageRateOfPay?: NexusGenScalars['BigInt'] | null; // BigInt
    prevailingWageRateOfPayUnit?: NexusGenEnums['payunit'] | null; // payunit
    receivedDate: NexusGenScalars['DateTime']; // DateTime!
    socCode: string; // String!
    visaClass: NexusGenEnums['visaclass']; // visaclass!
    wageRateOfPayFrom?: NexusGenScalars['BigInt'] | null; // BigInt
    wageRateOfPayTo?: NexusGenScalars['BigInt'] | null; // BigInt
    wageRateOfPayUnit?: NexusGenEnums['payunit'] | null; // payunit
    worksiteCity?: string | null; // String
    worksitePostalCode?: string | null; // String
    worksiteState?: string | null; // String
  }
  LCADisclosures: { // root type
    count: number; // Int!
    items: NexusGenRootTypes['LCADisclosure'][]; // [LCADisclosure!]!
  }
  Query: {};
  SOCJob: { // root type
    code: string; // ID!
    title: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Employer: { // field return type
    city: string; // String!
    naicsCode: string; // String!
    name: string; // String!
    postalCode: string; // String!
    state: string | null; // String
    uuid: string; // ID!
  }
  LCADisclosure: { // field return type
    beginDate: NexusGenScalars['DateTime']; // DateTime!
    caseNumber: string; // ID!
    caseStatus: NexusGenEnums['casestatus']; // casestatus!
    decisionDate: NexusGenScalars['DateTime']; // DateTime!
    employer: NexusGenRootTypes['Employer']; // Employer!
    fullTimePosition: boolean; // Boolean!
    jobTitle: string | null; // String
    prevailingWageRateOfPay: NexusGenScalars['BigInt'] | null; // BigInt
    prevailingWageRateOfPayUnit: NexusGenEnums['payunit'] | null; // payunit
    receivedDate: NexusGenScalars['DateTime']; // DateTime!
    socCode: string; // String!
    socJob: NexusGenRootTypes['SOCJob']; // SOCJob!
    visaClass: NexusGenEnums['visaclass']; // visaclass!
    wageRateOfPayFrom: NexusGenScalars['BigInt'] | null; // BigInt
    wageRateOfPayTo: NexusGenScalars['BigInt'] | null; // BigInt
    wageRateOfPayUnit: NexusGenEnums['payunit'] | null; // payunit
    worksiteCity: string | null; // String
    worksitePostalCode: string | null; // String
    worksiteState: string | null; // String
  }
  LCADisclosures: { // field return type
    count: number; // Int!
    items: NexusGenRootTypes['LCADisclosure'][]; // [LCADisclosure!]!
  }
  Query: { // field return type
    employers: NexusGenRootTypes['Employer'][]; // [Employer!]!
    lcaDisclosures: NexusGenRootTypes['LCADisclosures']; // LCADisclosures!
    socJobs: NexusGenRootTypes['SOCJob'][]; // [SOCJob!]!
  }
  SOCJob: { // field return type
    code: string; // ID!
    title: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Employer: { // field return type name
    city: 'String'
    naicsCode: 'String'
    name: 'String'
    postalCode: 'String'
    state: 'String'
    uuid: 'ID'
  }
  LCADisclosure: { // field return type name
    beginDate: 'DateTime'
    caseNumber: 'ID'
    caseStatus: 'casestatus'
    decisionDate: 'DateTime'
    employer: 'Employer'
    fullTimePosition: 'Boolean'
    jobTitle: 'String'
    prevailingWageRateOfPay: 'BigInt'
    prevailingWageRateOfPayUnit: 'payunit'
    receivedDate: 'DateTime'
    socCode: 'String'
    socJob: 'SOCJob'
    visaClass: 'visaclass'
    wageRateOfPayFrom: 'BigInt'
    wageRateOfPayTo: 'BigInt'
    wageRateOfPayUnit: 'payunit'
    worksiteCity: 'String'
    worksitePostalCode: 'String'
    worksiteState: 'String'
  }
  LCADisclosures: { // field return type name
    count: 'Int'
    items: 'LCADisclosure'
  }
  Query: { // field return type name
    employers: 'Employer'
    lcaDisclosures: 'LCADisclosures'
    socJobs: 'SOCJob'
  }
  SOCJob: { // field return type name
    code: 'ID'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Query: {
    employers: { // args
      searchStr?: string | null; // String
    }
    lcaDisclosures: { // args
      jobTitleSearchStr?: string | null; // String
      orderBy?: NexusGenInputs['LCADisclosureOrderByInput'][] | null; // [LCADisclosureOrderByInput!]
      skip?: number | null; // Int
      take: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}