server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /how {
    try_files /how/index.html =404;
  }

  location = /how/ {
    return 301 /how;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
