-- CreateTable
CREATE TABLE "users" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lca_disclosures" (
    "id" TEXT NOT NULL,
    "caseStatus" TEXT NOT NULL,
    "receivedDate" TIMESTAMP(3) NOT NULL,
    "decisionDate" TIMESTAMP(3) NOT NULL,
    "originalCertifiedDate" TIMESTAMP(3) NOT NULL,
    "visaClass" TEXT NOT NULL,
    "jobTitle" TEXT NOT NULL,
    "socCode" TEXT NOT NULL,
    "socTitle" TEXT NOT NULL,
    "fullTimePosition" BOOLEAN NOT NULL,
    "beginDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "totalWorkerPositions" INTEGER NOT NULL,
    "nNewEmployment" INTEGER NOT NULL,
    "nContinuedEmployment" INTEGER NOT NULL,
    "nChangePreviousEmployment" INTEGER NOT NULL,
    "nNewConcurrentEmployment" INTEGER NOT NULL,
    "nChangeEmployer" INTEGER NOT NULL,
    "nAmendedPetition" INTEGER NOT NULL,
    "employerName" TEXT NOT NULL,
    "tradeNameDba" TEXT NOT NULL,
    "employerAddress1" TEXT NOT NULL,
    "employerAddress2" TEXT NOT NULL,
    "employerCity" TEXT NOT NULL,
    "employerState" TEXT NOT NULL,
    "employerPostalCode" TEXT NOT NULL,
    "employerCountry" TEXT NOT NULL,
    "employerProvince" TEXT NOT NULL,
    "employerPhone" TEXT NOT NULL,
    "employerPhoneExt" TEXT NOT NULL,
    "naicsCode" TEXT NOT NULL,
    "employerPocLastName" TEXT NOT NULL,
    "employerPocFirstName" TEXT NOT NULL,
    "employerPocMiddleName" TEXT NOT NULL,
    "employerPocJobTitle" TEXT NOT NULL,
    "employerPocAddress1" TEXT NOT NULL,
    "employerPocAddress2" TEXT NOT NULL,
    "employerPocCity" TEXT NOT NULL,
    "employerPocState" TEXT NOT NULL,
    "employerPocPostalCode" TEXT NOT NULL,
    "employerPocCountry" TEXT NOT NULL,
    "employerPocProvince" TEXT NOT NULL,
    "employerPocPhone" TEXT NOT NULL,
    "employerPocPhoneExt" TEXT NOT NULL,
    "employerPocEmail" TEXT NOT NULL,
    "agentRepresentingEmployer" BOOLEAN NOT NULL,
    "agentAttorneyLastName" TEXT NOT NULL,
    "agentAttorneyFirstName" TEXT NOT NULL,
    "agentAttorneyMiddleName" TEXT NOT NULL,
    "agentAttorneyAddress1" TEXT NOT NULL,
    "agentAttorneyAddress2" TEXT NOT NULL,
    "agentAttorneyCity" TEXT NOT NULL,
    "agentAttorneyState" TEXT NOT NULL,
    "agentAttorneyPostalCode" TEXT NOT NULL,
    "agentAttorneyCountry" TEXT NOT NULL,
    "agentAttorneyProvince" TEXT NOT NULL,
    "agentAttorneyPhone" TEXT NOT NULL,
    "agentAttorneyPhoneExt" TEXT NOT NULL,
    "agentAttorneyEmail" TEXT NOT NULL,
    "lawfirmNameBusinessName" TEXT NOT NULL,
    "stateOfHighestCourt" TEXT NOT NULL,
    "nameOfHighestStateCourt" TEXT NOT NULL,
    "nWorksiteWorkers" INTEGER NOT NULL,
    "secondaryEntity" BOOLEAN NOT NULL,
    "secondaryEntityBusinessName" TEXT NOT NULL,
    "worksiteAddress1" TEXT NOT NULL,
    "worksiteAddress2" TEXT NOT NULL,
    "worksiteCity" TEXT NOT NULL,
    "worksiteCounty" TEXT NOT NULL,
    "worksiteState" TEXT NOT NULL,
    "worksitePostalCode" TEXT NOT NULL,
    "wageRateOfPayFrom" DECIMAL(65,30) NOT NULL,
    "wageRateOfPayTo" DECIMAL(65,30) NOT NULL,
    "wageUnitOfPay" TEXT NOT NULL,
    "prevailingWage" DECIMAL(65,30) NOT NULL,
    "pwUnitOfPay" TEXT NOT NULL,
    "pwTrackingNumber" TEXT NOT NULL,
    "pwWageLeve" TEXT NOT NULL,
    "pwOesYearStartDate" TIMESTAMP(3) NOT NULL,
    "pwOesYearEndDate" TIMESTAMP(3) NOT NULL,
    "pwOtherSource" TEXT NOT NULL,
    "pwOtherYear" INTEGER NOT NULL,
    "pwSurveyPublisher" TEXT NOT NULL,
    "pwSurveyName" TEXT NOT NULL,
    "totalWorksiteLocations" INTEGER NOT NULL,
    "agreeToLcStatement" BOOLEAN NOT NULL,
    "h1bDependent" BOOLEAN NOT NULL,
    "willfulViolator" BOOLEAN NOT NULL,
    "supportH1b" BOOLEAN NOT NULL,
    "statutoryBasis" TEXT NOT NULL,
    "appendixAAttached" BOOLEAN NOT NULL,
    "publicDisclosure" TEXT NOT NULL,
    "preparerLastName" TEXT NOT NULL,
    "preparerFirstName" TEXT NOT NULL,
    "preparerMiddleInitial" TEXT NOT NULL,
    "preparerBusinessName" TEXT NOT NULL,
    "preparerEmail" TEXT NOT NULL,

    CONSTRAINT "lca_disclosures_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
