name: Build and deploy Vite React App (/react-client)

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true
#2
env:
  IMAGE_NAME: "lca-data-react-app"
  DOCKER_PORT: 80
  SUBFOLDER: "react-client"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $IMAGE_NAME):latest ./$(echo $SUBFOLDER)

      - name: Save the image to a tar.gz
        run: docker save $(echo $IMAGE_NAME):latest | gzip > client.tar.gz

      - name: List files in the current directory
        run: ls -al

      - name: Use SCP to push tar.gz to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          source: "client.tar.gz"
          target: /home/${{ secrets.DIGITALOCEAN_SSH_USERNAME }}/docker-images/

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          envs: IMAGE_NAME,DOCKER_PORT
          script: |
            # Stop running container
            docker stop $(echo $IMAGE_NAME)
            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            # Remove old image
            docker rmi $(echo $IMAGE_NAME):latest
            # Load the image from the tar.gz
            docker load < /home/${{ secrets.DIGITALOCEAN_SSH_USERNAME }}/docker-images/client.tar.gz
            # Remove the tar.gz file
            rm /home/${{ secrets.DIGITALOCEAN_SSH_USERNAME }}/docker-images/client.tar.gz
