name: Docker compose up server and client

# 1
# Controls when the workflow will run
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#3
jobs:
  copy_compose_yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use SCP to push docker-compose-server-client.yml to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          source: "docker-compose-server-client.yml"
          target: /home/${{ secrets.DIGITALOCEAN_SSH_USERNAME }}/docker/

  deploy:
    runs-on: ubuntu-latest
    needs: copy_compose_yml
    steps:
      - name: Runs docker compose up for server and client
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          script: |
            # Restart containers
            cd /home/${{ secrets.DIGITALOCEAN_SSH_USERNAME }}/docker
            docker compose -f docker-compose-server-client.yml down
            docker compose -f docker-compose-server-client.yml up -d
